#!/bin/sh

# Build and run two RuiFlex examples: normal, reentrant.

cd normal
echo "Building and running normal..."
rake -f ../rakefile.rb clean
rake -f ../rakefile.rb
normal

cd ..

cd reentrant
echo "Building and running reentrant..."
rake -f ../rakefile.rb clean
rake -f ../rakefile.rb
reentrant

cd ..

cd ruigen
echo "Creating custom output..."
ruiflex -f n_flex.rb -n -g custom.rb

cd ..
